const mockData = [
  {
    id: "trip1",
    title: "Spiritual & Adventure Escape",
    dates: ["2025-06-01", "2025-06-07"],
    destination: "Uttarakhand, India",
    completed: false,
    days: [
      {
        id: "day1",
        title: "Day 1 - Arrival in Haridwar",
        date: "2025-06-01",
        activities: [
          {
            id: "act1",
            time: "04:00",
            title: "Ganga Dip at Har ki Pauri",
            description:
              "Participate in an early morning holy dip in the Ganges River at Har ki Pauri Ghat.",
            location: "Har ki Pauri, Haridwar",
            category: "Spiritual",
            cost: 0,
            completed: true,
            notCompleted: false,
            reminder: false,
            notes:
              "Wear comfortable clothing; towels provided by local vendors.",
            latitude: 29.9567,
            longitude: 78.1709,
          },
          {
            id: "act2",
            time: "06:00",
            title: "Mansa Devi Temple Trek",
            description:
              "Trek or take the cable car to Mansa Devi Temple for blessings and scenic views.",
            location: "Mansa Devi Temple, Haridwar",
            category: "Spiritual",
            cost: 150,
            completed: false,
            notCompleted: false,
            reminder: true,
            notes: "Carry water; trek takes ~1 hour.",
            latitude: 29.9588,
            longitude: 78.1645,
          },
          {
            id: "act3",
            time: "08:00",
            title: "Breakfast at Local Eatery",
            description:
              "Enjoy a traditional North Indian breakfast at Chotiwala or similar.",
            location: "Chotiwala Restaurant, Haridwar",
            category: "Dining",
            cost: 120,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Try aloo puri or paratha.",
            latitude: 29.9473,
            longitude: 78.1602,
          },
          {
            id: "act4",
            time: "10:00",
            title: "Visit Maya Devi Temple",
            description:
              "Explore the ancient Maya Devi Temple, a significant Shakti Peeth.",
            location: "Maya Devi Temple, Haridwar",
            category: "Spiritual",
            cost: 0,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Photography may be restricted.",
            latitude: 29.9481,
            longitude: 78.1575,
          },
          {
            id: "act5",
            time: "12:00",
            title: "Chandi Devi Temple Visit",
            description:
              "Travel by taxi and cable car to Chandi Devi Temple atop Neel Parvat.",
            location: "Chandi Devi Temple, Haridwar",
            category: "Spiritual",
            cost: 300,
            completed: false,
            notCompleted: false,
            reminder: true,
            notes: "Book taxi in advance.",
            latitude: 29.9757,
            longitude: 78.1793,
          },
          {
            id: "act6",
            time: "15:00",
            title: "Lunch at Hoshiyarpuri",
            description:
              "Savor a hearty Punjabi meal at Hoshiyarpuri Restaurant.",
            location: "Hoshiyarpuri Restaurant, Haridwar",
            category: "Dining",
            cost: 200,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Vegetarian options available.",
            latitude: 29.9436,
            longitude: 78.1612,
          },
          {
            id: "act7",
            time: "18:30",
            title: "Ganga Aarti at Har ki Pauri",
            description:
              "Witness the mesmerizing Ganga Aarti ceremony at dusk.",
            location: "Har ki Pauri, Haridwar",
            category: "Spiritual",
            cost: 0,
            completed: false,
            notCompleted: false,
            reminder: true,
            notes: "Arrive early for a good spot.",
            latitude: 29.9567,
            longitude: 78.1709,
          },
          {
            id: "act8",
            time: "20:00",
            title: "Train to Rishikesh",
            description:
              "Board an evening train to Rishikesh; have dinner on board.",
            location: "Haridwar Railway Station",
            category: "Travel",
            cost: 250,
            completed: false,
            notCompleted: false,
            reminder: true,
            notes: "Book AC chair car for comfort.",
            latitude: 29.949,
            longitude: 78.1437,
          },
        ],
      },
      {
        id: "day2",
        title: "Day 2 - Rishikesh Exploration",
        date: "2025-06-02",
        activities: [
          {
            id: "act9",
            time: "06:30",
            title: "Yoga Session at Parmarth Niketan",
            description:
              "Join a morning yoga and meditation session by the Ganges.",
            location: "Parmarth Niketan Ashram, Rishikesh",
            category: "Wellness",
            cost: 200,
            completed: false,
            notCompleted: false,
            reminder: true,
            notes: "Bring your own yoga mat.",
            latitude: 30.1198,
            longitude: 78.3175,
          },
          {
            id: "act10",
            time: "08:30",
            title: "Breakfast at Little Buddha Cafe",
            description: "Enjoy a healthy breakfast with a view of the Ganges.",
            location: "Little Buddha Cafe, Laxman Jhula, Rishikesh",
            category: "Dining",
            cost: 150,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Try their smoothie bowls.",
            latitude: 30.1259,
            longitude: 78.3291,
          },
          {
            id: "act11",
            time: "10:00",
            title: "Laxman Jhula & Ram Jhula Walk",
            description:
              "Stroll across the iconic suspension bridges and explore nearby temples.",
            location: "Laxman Jhula, Rishikesh",
            category: "Sightseeing",
            cost: 0,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Wear comfortable shoes.",
            latitude: 30.1254,
            longitude: 78.3302,
          },
          {
            id: "act12",
            time: "12:30",
            title: "White Water Rafting",
            description:
              "Experience thrilling rafting on the Ganges with a professional guide.",
            location: "Shivpuri, Rishikesh",
            category: "Adventure",
            cost: 1500,
            completed: false,
            notCompleted: false,
            reminder: true,
            notes:
              "Book with a reputable operator like Himalayan River Runners.",
            latitude: 30.1378,
            longitude: 78.3289,
          },
          {
            id: "act13",
            time: "15:30",
            title: "Lunch at Bistro Nirvana",
            description: "Relish a post-rafting meal at Bistro Nirvana.",
            location: "Bistro Nirvana, Rishikesh",
            category: "Dining",
            cost: 250,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Try their wood-fired pizzas.",
            latitude: 30.1205,
            longitude: 78.316,
          },
          {
            id: "act14",
            time: "17:00",
            title: "Triveni Ghat Aarti",
            description: "Attend the evening Ganga Aarti at Triveni Ghat.",
            location: "Triveni Ghat, Rishikesh",
            category: "Spiritual",
            cost: 0,
            completed: false,
            notCompleted: false,
            reminder: true,
            notes: "Less crowded than Parmarth Niketan.",
            latitude: 30.1036,
            longitude: 78.2946,
          },
          {
            id: "act15",
            time: "19:00",
            title: "Dinner at AyurPak",
            description:
              "Enjoy an Ayurvedic-inspired dinner at AyurPak Restaurant.",
            location: "AyurPak, Rishikesh",
            category: "Dining",
            cost: 200,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Organic and vegan options available.",
            latitude: 30.123,
            longitude: 78.3225,
          },
        ],
      },
      {
        id: "day3",
        title: "Day 3 - Rishikesh Adventure",
        date: "2025-06-03",
        activities: [
          {
            id: "act16",
            time: "05:30",
            title: "Kunjapuri Temple Sunrise",
            description:
              "Trek to Kunjapuri Temple for a breathtaking sunrise view.",
            location: "Kunjapuri Temple, Rishikesh",
            category: "Sightseeing",
            cost: 300,
            completed: false,
            notCompleted: false,
            reminder: true,
            notes: "Carry a light jacket; early start.",
            latitude: 30.172,
            longitude: 78.38,
          },
          {
            id: "act17",
            time: "08:30",
            title: "Breakfast at The Sitting Elephant",
            description:
              "Have breakfast at this riverside cafe with stunning views.",
            location: "The Sitting Elephant, Rishikesh",
            category: "Dining",
            cost: 180,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Try their pancakes.",
            latitude: 30.1208,
            longitude: 78.315,
          },
          {
            id: "act18",
            time: "10:00",
            title: "Neelkanth Mahadev Temple",
            description:
              "Visit the sacred Neelkanth Mahadev Temple amidst lush forests.",
            location: "Neelkanth Mahadev Temple, Rishikesh",
            category: "Spiritual",
            cost: 200,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Carry water for the journey.",
            latitude: 30.0647,
            longitude: 78.377,
          },
          {
            id: "act19",
            time: "13:00",
            title: "Lunch at Cafe de Goa",
            description: "Enjoy a relaxed lunch with Goan flavors.",
            location: "Cafe de Goa, Rishikesh",
            category: "Dining",
            cost: 250,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Great for seafood lovers.",
            latitude: 30.1265,
            longitude: 78.33,
          },
          {
            id: "act20",
            time: "15:00",
            title: "Vashishta Cave Meditation",
            description: "Meditate in the serene Vashishta Cave by the Ganges.",
            location: "Vashishta Cave, Rishikesh",
            category: "Wellness",
            cost: 100,
            completed: false,
            notCompleted: false,
            reminder: true,
            notes: "Maintain silence inside the cave.",
            latitude: 30.169,
            longitude: 78.36,
          },
          {
            id: "act21",
            time: "18:00",
            title: "Ganga Aarti at Parmarth Niketan",
            description:
              "Experience the grand Ganga Aarti at Parmarth Niketan Ashram.",
            location: "Parmarth Niketan, Rishikesh",
            category: "Spiritual",
            cost: 0,
            completed: false,
            notCompleted: false,
            reminder: true,
            notes: "Arrive by 17:45 for seating.",
            latitude: 30.1198,
            longitude: 78.3175,
          },
          {
            id: "act22",
            time: "20:00",
            title: "Dinner at The Chotiwala",
            description: "Dine at the famous Chotiwala for a traditional meal.",
            location: "The Chotiwala, Rishikesh",
            category: "Dining",
            cost: 200,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Busy in evenings; book a table.",
            latitude: 30.1235,
            longitude: 78.32,
          },
        ],
      },
      {
        id: "day4",
        title: "Day 4 - Devprayag Excursion",
        date: "2025-06-04",
        activities: [
          {
            id: "act23",
            time: "06:30",
            title: "Travel to Devprayag",
            description:
              "Take a shared taxi or bus to Devprayag, the confluence of Alaknanda and Bhagirathi rivers.",
            location: "Devprayag, Uttarakhand",
            category: "Travel",
            cost: 400,
            completed: false,
            notCompleted: false,
            reminder: true,
            notes: "Journey takes ~2 hours.",
            latitude: 30.146,
            longitude: 78.598,
          },
          {
            id: "act24",
            time: "09:00",
            title: "Visit Sangam",
            description:
              "Take a dip at the holy confluence of the rivers and offer prayers.",
            location: "Sangam, Devprayag",
            category: "Spiritual",
            cost: 0,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Follow local customs.",
            latitude: 30.1465,
            longitude: 78.5975,
          },
          {
            id: "act25",
            time: "10:30",
            title: "Raghunathji Temple",
            description:
              "Explore the ancient Raghunathji Temple dedicated to Lord Rama.",
            location: "Raghunathji Temple, Devprayag",
            category: "Spiritual",
            cost: 0,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Respect temple etiquette.",
            latitude: 30.1462,
            longitude: 78.5985,
          },
          {
            id: "act26",
            time: "12:30",
            title: "Lunch at Local Dhaba",
            description: "Enjoy a simple yet delicious meal at a local dhaba.",
            location: "Devprayag",
            category: "Dining",
            cost: 150,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Try thali for variety.",
            latitude: 30.1455,
            longitude: 78.599,
          },
          {
            id: "act27",
            time: "14:00",
            title: "Explore Devprayag Streets",
            description:
              "Walk through the serene streets and interact with locals.",
            location: "Devprayag Town",
            category: "Sightseeing",
            cost: 0,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Great for photography.",
            latitude: 30.146,
            longitude: 78.598,
          },
          {
            id: "act28",
            time: "16:30",
            title: "Return to Rishikesh",
            description: "Travel back to Rishikesh by taxi or bus.",
            location: "Devprayag to Rishikesh",
            category: "Travel",
            cost: 0,
            completed: false,
            notCompleted: false,
            reminder: true,
            notes: "Confirm return transport.",
            latitude: 30.146,
            longitude: 78.598,
          },
          {
            id: "act29",
            time: "19:00",
            title: "Dinner at Green Hotel",
            description:
              "Relax with a hearty dinner at Green Hotel Restaurant.",
            location: "Green Hotel, Rishikesh",
            category: "Dining",
            cost: 200,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Close to most hotels.",
            latitude: 30.122,
            longitude: 78.318,
          },
        ],
      },
      {
        id: "day5",
        title: "Day 5 - Rishikesh Adventure & Shopping",
        date: "2025-06-05",
        activities: [
          {
            id: "act30",
            time: "06:00",
            title: "Bungee Jumping",
            description:
              "Experience India’s highest bungee jump at Jumpin Heights.",
            location: "Jumpin Heights, Rishikesh",
            category: "Adventure",
            cost: 4000,
            completed: false,
            notCompleted: false,
            reminder: true,
            notes: "Pre-booking required; age and weight restrictions apply.",
            latitude: 30.2239,
            longitude: 78.4427,
          },
          {
            id: "act31",
            time: "09:30",
            title: "Breakfast at Cafe de Goa",
            description: "Recharge with a hearty breakfast post-adventure.",
            location: "Cafe de Goa, Rishikesh",
            category: "Dining",
            cost: 180,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Try their omelettes.",
            latitude: 30.1265,
            longitude: 78.33,
          },
          {
            id: "act32",
            time: "11:00",
            title: "Local Market Shopping",
            description:
              "Shop for souvenirs, handicrafts, and spiritual items at Rishikesh Market.",
            location: "Rishikesh Main Market",
            category: "Shopping",
            cost: 1000,
            completed: false,
            notCompleted: false,
            reminder: true,
            notes: "Bargain politely.",
            latitude: 30.123,
            longitude: 78.3205,
          },
          {
            id: "act33",
            time: "13:30",
            title: "Lunch at The Sitting Elephant",
            description: "Enjoy a leisurely lunch by the river.",
            location: "The Sitting Elephant, Rishikesh",
            category: "Dining",
            cost: 200,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Great ambiance.",
            latitude: 30.1208,
            longitude: 78.315,
          },
          {
            id: "act34",
            time: "15:00",
            title: "Beatles Ashram Visit",
            description:
              "Explore the historic Beatles Ashram, famous for their 1968 stay.",
            location: "Maharishi Mahesh Yogi’s Ashram, Rishikesh",
            category: "Sightseeing",
            cost: 150,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Check out the graffiti art.",
            latitude: 30.1157,
            longitude: 78.3137,
          },
          {
            id: "act35",
            time: "17:30",
            title: "Relax by Ganges",
            description: "Spend time relaxing or journaling by the Ganges.",
            location: "Ganga Ghat, Rishikesh",
            category: "Relaxation",
            cost: 0,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Bring a book or journal.",
            latitude: 30.12,
            longitude: 78.3167,
          },
          {
            id: "act36",
            time: "19:30",
            title: "Farewell Dinner",
            description:
              "Celebrate the trip with a special dinner at Little Buddha Cafe.",
            location: "Little Buddha Cafe, Rishikesh",
            category: "Dining",
            cost: 300,
            completed: false,
            notCompleted: false,
            reminder: true,
            notes: "Reserve a rooftop table.",
            latitude: 30.1259,
            longitude: 78.3291,
          },
        ],
      },
      {
        id: "day6",
        title: "Day 6 - Return Journey",
        date: "2025-06-06",
        activities: [
          {
            id: "act37",
            time: "07:00",
            title: "Morning Walk by Ganges",
            description:
              "Take a final serene walk along the Ganges before departure.",
            location: "Ganga Ghat, Rishikesh",
            category: "Relaxation",
            cost: 0,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Perfect for photography.",
            latitude: 30.12,
            longitude: 78.3167,
          },
          {
            id: "act38",
            time: "08:30",
            title: "Breakfast at Bistro Nirvana",
            description: "Enjoy a final breakfast in Rishikesh.",
            location: "Bistro Nirvana, Rishikesh",
            category: "Dining",
            cost: 180,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Quick service.",
            latitude: 30.1205,
            longitude: 78.316,
          },
          {
            id: "act39",
            time: "10:00",
            title: "Check Out & Travel to Delhi",
            description:
              "Check out from hotel and board a bus or train to Delhi.",
            location: "Rishikesh to Delhi",
            category: "Travel",
            cost: 800,
            completed: false,
            notCompleted: false,
            reminder: true,
            notes: "Book Volvo bus for comfort.",
            latitude: 30.0869,
            longitude: 78.2676,
          },
          {
            id: "act40",
            time: "16:00",
            title: "Lunch En Route",
            description: "Stop for lunch at a highway dhaba en route to Delhi.",
            location: "Highway Dhaba",
            category: "Dining",
            cost: 150,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Try local specialties.",
            latitude: null,
            longitude: null,
          },
        ],
      },
    ],
  },
  {
    id: "trip2",
    title: "Himalayan Retreat",
    dates: ["2025-07-15", "2025-07-20"],
    destination: "Himachal Pradesh, India",
    completed: false,
    days: [
      {
        id: "day7",
        title: "Day 1 - Arrival in Manali",
        date: "2025-07-15",
        activities: [
          {
            id: "act41",
            time: "08:00",
            title: "Arrive in Manali",
            description:
              "Reach Manali by overnight bus from Delhi; check into hotel.",
            location: "Manali, Himachal Pradesh",
            category: "Travel",
            cost: 1200,
            completed: false,
            notCompleted: false,
            reminder: true,
            notes: "Carry warm clothing.",
            latitude: 32.2396,
            longitude: 77.1887,
          },
          {
            id: "act42",
            time: "10:00",
            title: "Breakfast at Cafe 1947",
            description:
              "Start the day with a hearty breakfast by the Beas River.",
            location: "Cafe 1947, Manali",
            category: "Dining",
            cost: 200,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Try their waffles.",
            latitude: 32.243,
            longitude: 77.189,
          },
          {
            id: "act43",
            time: "11:30",
            title: "Hadimba Temple Visit",
            description:
              "Explore the ancient Hadimba Devi Temple surrounded by cedar forests.",
            location: "Hadimba Temple, Manali",
            category: "Spiritual",
            cost: 0,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Wear modest clothing.",
            latitude: 32.2486,
            longitude: 77.1818,
          },
          {
            id: "act44",
            time: "14:00",
            title: "Lunch at Johnson’s Cafe",
            description: "Enjoy a delicious lunch at Johnson’s Cafe.",
            location: "Johnson’s Cafe, Manali",
            category: "Dining",
            cost: 250,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Try their trout dishes.",
            latitude: 32.2425,
            longitude: 77.188,
          },
          {
            id: "act45",
            time: "16:00",
            title: "Mall Road Stroll",
            description:
              "Walk along Mall Road, shop for souvenirs, and enjoy the vibe.",
            location: "Mall Road, Manali",
            category: "Shopping",
            cost: 500,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Look for woolen shawls.",
            latitude: 32.241,
            longitude: 77.1875,
          },
          {
            id: "act46",
            time: "19:00",
            title: "Dinner at The Lazy Dog",
            description:
              "Dine at The Lazy Dog with live music and great ambiance.",
            location: "The Lazy Dog, Manali",
            category: "Dining",
            cost: 300,
            completed: false,
            notCompleted: false,
            reminderificando: false,
            notes: "Book a table in advance.",
            latitude: 32.2435,
            longitude: 77.1895,
          },
        ],
      },
      {
        id: "day8",
        title: "Day 2 - Rohtang Pass Adventure",
        date: "2025-07-16",
        activities: [
          {
            id: "act47",
            time: "06:00",
            title: "Travel to Rohtang Pass",
            description:
              "Depart early for Rohtang Pass; enjoy snow activities.",
            location: "Rohtang Pass, Manali",
            category: "Adventure",
            cost: 2000,
            completed: false,
            notCompleted: false,
            reminder: true,
            notes: "Carry sunglasses and sunscreen.",
            latitude: 32.3643,
            longitude: 77.2167,
          },
          {
            id: "act48",
            time: "12:00",
            title: "Lunch at Rohtang",
            description: "Have a packed lunch amidst the snowy mountains.",
            location: "Rohtang Pass",
            category: "Dining",
            cost: 150,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Pack from hotel.",
            latitude: 32.3643,
            longitude: 77.2167,
          },
          {
            id: "act49",
            time: "15:00",
            title: "Return to Manali",
            description: "Drive back to Manali; relax at hotel.",
            location: "Manali",
            category: "Travel",
            cost: 0,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Rest after a long day.",
            latitude: 32.2396,
            longitude: 77.1887,
          },
          {
            id: "act50",
            time: "19:00",
            title: "Dinner at Il Forno",
            description:
              "Enjoy Italian cuisine at Il Forno with mountain views.",
            location: "Il Forno, Manali",
            category: "Dining",
            cost: 300,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Try their pizzas.",
            latitude: 32.244,
            longitude: 77.19,
          },
        ],
      },
      {
        id: "day9",
        title: "Day 3 - Travel to Kasol",
        date: "2025-07-17",
        activities: [
          {
            id: "act51",
            time: "08:00",
            title: "Travel to Kasol",
            description:
              "Take a bus to Kasol, the hippie haven in Parvati Valley.",
            location: "Kasol, Himachal Pradesh",
            category: "Travel",
            cost: 400,
            completed: false,
            notCompleted: false,
            reminder: true,
            notes: "Journey takes ~4 hours.",
            latitude: 32.0096,
            longitude: 77.3153,
          },
          {
            id: "act52",
            time: "13:00",
            title: "Lunch at Moon Dance Cafe",
            description: "Savor Israeli and local dishes at Moon Dance Cafe.",
            location: "Moon Dance Cafe, Kasol",
            category: "Dining",
            cost: 200,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Try their falafel.",
            latitude: 32.01,
            longitude: 77.3145,
          },
          {
            id: "act53",
            time: "15:00",
            title: "Parvati River Walk",
            description:
              "Stroll along the Parvati River and enjoy the serene views.",
            location: "Parvati River, Kasol",
            category: "Relaxation",
            cost: 0,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Great for photography.",
            latitude: 32.009,
            longitude: 77.316,
          },
          {
            id: "act54",
            time: "18:00",
            title: "Explore Kasol Market",
            description:
              "Shop for bohemian clothes and accessories in Kasol Market.",
            location: "Kasol Market",
            category: "Shopping",
            cost: 700,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Bargain for better deals.",
            latitude: 32.0105,
            longitude: 77.314,
          },
          {
            id: "act55",
            time: "20:00",
            title: "Dinner at Evergreen Cafe",
            description: "Dine at Evergreen Cafe, known for its vibrant vibe.",
            location: "Evergreen Cafe, Kasol",
            category: "Dining",
            cost: 250,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Try their pastas.",
            latitude: 32.0102,
            longitude: 77.3148,
          },
        ],
      },
      {
        id: "day10",
        title: "Day 4 - Kheerganga Trek",
        date: "2025-07-18",
        activities: [
          {
            id: "act56",
            time: "06:30",
            title: "Start Kheerganga Trek",
            description:
              "Begin the trek to Kheerganga; enjoy hot springs at the top.",
            location: "Kheerganga, Parvati Valley",
            category: "Adventure",
            cost: 1000,
            completed: false,
            notCompleted: false,
            reminder: true,
            notes: "Carry trekking gear and snacks.",
            latitude: 32.06,
            longitude: 77.35,
          },
          {
            id: "act57",
            time: "12:00",
            title: "Lunch at Kheerganga",
            description: "Have a packed lunch during the trek.",
            location: "Kheerganga",
            category: "Dining",
            cost: 150,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Pack from Kasol.",
            latitude: 32.06,
            longitude: 77.35,
          },
          {
            id: "act58",
            time: "15:00",
            title: "Relax in Hot Springs",
            description: "Soak in the natural hot springs at Kheerganga.",
            location: "Kheerganga Hot Springs",
            category: "Relaxation",
            cost: 0,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Bring swimwear.",
            latitude: 32.0605,
            longitude: 77.3495,
          },
          {
            id: "act59",
            time: "18:00",
            title: "Camping at Kheerganga",
            description: "Spend the night camping under the stars.",
            location: "Kheerganga Campsite",
            category: "Adventure",
            cost: 800,
            completed: false,
            notCompleted: false,
            reminder: true,
            notes: "Book campsite in advance.",
            latitude: 32.06,
            longitude: 77.35,
          },
        ],
      },
      {
        id: "day11",
        title: "Day 5 - Return to Kasol",
        date: "2025-07-19",
        activities: [
          {
            id: "act60",
            time: "06:30",
            title: "Trek Back to Barshaini",
            description: "Descend from Kheerganga to Barshaini.",
            location: "Kheerganga to Barshaini",
            category: "Adventure",
            cost: 0,
            completed: false,
            notCompleted: false,
            reminder: true,
            notes: "Start early to avoid heat.",
            latitude: 32.0333,
            longitude: 77.3333,
          },
          {
            id: "act61",
            time: "11:00",
            title: "Travel to Kasol",
            description: "Take a taxi from Barshaini to Kasol.",
            location: "Barshaini to Kasol",
            category: "Travel",
            cost: 200,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Short ride.",
            latitude: 32.0096,
            longitude: 77.3153,
          },
          {
            id: "act62",
            time: "12:30",
            title: "Lunch at Jim Morrison Cafe",
            description: "Relax with a meal at Jim Morrison Cafe.",
            location: "Jim Morrison Cafe, Kasol",
            category: "Dining",
            cost: 200,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Great music and vibe.",
            latitude: 32.0098,
            longitude: 77.3142,
          },
          {
            id: "act63",
            time: "15:00",
            title: "Visit Manikaran Sahib",
            description: "Explore the Gurudwara and hot springs at Manikaran.",
            location: "Manikaran, Himachal Pradesh",
            category: "Spiritual",
            cost: 100,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Respect religious customs.",
            latitude: 32.027,
            longitude: 77.3475,
          },
          {
            id: "act64",
            time: "18:00",
            title: "Dinner at Moon Dance Cafe",
            description: "Enjoy a final dinner in Kasol.",
            location: "Moon Dance Cafe, Kasol",
            category: "Dining",
            cost: 250,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Try their desserts.",
            latitude: 32.01,
            longitude: 77.3145,
          },
        ],
      },
      {
        id: "day12",
        title: "Day 6 - Return to Delhi",
        date: "2025-07-20",
        activities: [
          {
            id: "act65",
            time: "08:00",
            title: "Breakfast at Evergreen Cafe",
            description: "Have a quick breakfast before departure.",
            location: "Evergreen Cafe, Kasol",
            category: "Dining",
            cost: 180,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Pack some snacks for the journey.",
            latitude: 32.0102,
            longitude: 77.3148,
          },
          {
            id: "act66",
            time: "09:00",
            title: "Bus to Delhi",
            description: "Board a bus back to Delhi; overnight journey.",
            location: "Kasol to Delhi",
            category: "Travel",
            cost: 1200,
            completed: false,
            notCompleted: false,
            reminder: true,
            notes: "Book in advance.",
            latitude: 32.0096,
            longitude: 77.3153,
          },
          {
            id: "act67",
            time: "14:00",
            title: "Lunch En Route",
            description: "Stop for lunch at a highway restaurant.",
            location: "Highway Restaurant",
            category: "Dining",
            cost: 150,
            completed: false,
            notCompleted: false,
            reminder: false,
            notes: "Quick stop.",
            latitude: null,
            longitude: null,
          },
        ],
      },
    ],
  },
];

window.mockData = mockData;
